import { type NextPage } from "next";
import Head from "next/head";
import RoomList from "../components/room/RoomList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-8 ml-8 mr-8 flex flex-col">
        <h1 className="bg-gradient-to-r from-[var(--purple-one)] to-[var(--purple-three)] bg-clip-text text-center text-8xl font-extrabold text-transparent">
          TicTacToe
        </h1>
        <RoomList />
      </main>
    </>
  );
};

export default Home;
