import { type NextPage } from "next";
import Head from "next/head";
import RoomList from "../components/room/RoomList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-8 ml-8 mr-8 flex flex-col">
        <h1 className="text-center text-xl font-semibold mb-10">Tac Tac Toe</h1>
        <RoomList />
      </main>
    </>
  );
};

export default Home;
